GET http://localhost:5000/api/v1/twitch/categories/all
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"dnjsskarb123",
    "password":"dnjsskarb123",
    "email":"dnjsskarb123@gmail.com"
}
###