GET http://localhost:3000/api/v1/twitch/streams
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username":"dnjsskarb123",
    "password":"dnjsskarb123",
    "email":"dnjsskarb123@gmail.com"
}
###