GET http://localhost:5000/auth/signup
###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username":"dnjsskarb123df",
    "password":"dnjsskarb123df",
    "email":"dnjsskarb123@gmail.com"
}